services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "5001:5001"
    depends_on:
      - user-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge